application:
  subdomain: restreamer
  background_task: true
  usb_accel: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://restreamer:8080/
  ingress:
    - protocol: tcp
      port: 1935
      service: restreamer
    - protocol: tcp
      port: 1936
      service: restreamer
    - protocol: udp
      port: 6000
      service: restreamer
services:
  restreamer:
    # upstream: datarhei/restreamer:2.12.0
    image: docker.1ms.run/datarhei/restreamer:2.12.0
    binds:
      - /lzcapp/var/config:/core/config
      - /lzcapp/var/data:/core/data
